---
- hosts: devops1
  become: yes
  tasks:
 
  - name: Add user2 to remote hosts
    become: yes
    user: 
      name: user2 
      home: /home/user2
      shell: /bin/bash

  - name: Add user3 to remote hosts
    become: yes
    user: 
      name: user3
      home: /home/user3
      shell: /bin/bash

  - name: create group "superusers"
    become: yes
    group:
      name: superusers
      state: present

  - name: add user2 to new group "superusers"
    become: yes
    user:
      name: user2
      groups: superusers
      append: yes

  - name: add user3 to new group "superusers"
    become: yes
    user:
      name: user3
      groups: superusers
      append: yes

  - name: Add SSH keys for User2 to remote hosts
    become: yes
    authorized_key: 
      user: user2 
      key: "{{ lookup('file', '/root/.ssh/user2.pub') }}"

  - name: Add SSH keys for User3 to remote hosts
    become: yes
    authorized_key: 
      user: user3
      key: "{{ lookup('file', '/root/.ssh/user3.pub') }}"

  - name: Adding User2 to sudoers
    become: yes
    lineinfile:
      dest: /etc/sudoers
      line: "user2 ALL=(ALL)  NOPASSWD: ALL"
      validate: 'visudo -cf %s'

  - name: Adding User3 to sudoers
    become: yes
    lineinfile:
      dest: /etc/sudoers
      line: "user3 ALL=(ALL)  NOPASSWD: ALL"
      validate: 'visudo -cf %s'
